name: Upload Model

on:
  push:
    tags:
      - "v*"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: "3.12"

      - name: Update pip
        run: |
          python -m pip install --upgrade pip

      - name: Install PyTorch
        run: |
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Get model and tokenizer
        run: |
          python get_model.py tiny-clinicalbert-qa.tar.gz

      - name: Upload model and tokenizer
        uses: softprops/action-gh-release@v2
        with:
          files: |
            tiny-clinicalbert-qa.tar.gz
